// One-shot generator: reads contracts/deployments/base-sepolia.json + forge ABI artifacts
// and emits shared/deployments.ts. Run with: pnpm gen  (after every deploy).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const deployments = JSON.parse(readFileSync(join(root, "contracts/deployments/base-sepolia.json"), "utf8"));

interface AbiEntry {
  type: string;
  name?: string;
}

function loadAbi(artifact: string, names: string[] | null): AbiEntry[] {
  const j = JSON.parse(readFileSync(join(root, "contracts/out", artifact), "utf8"));
  const abi: AbiEntry[] = j.abi;
  if (!names) return abi.filter((e) => e.type === "function");
  const keep = new Set(names);
  const out = abi.filter((e) => e.type === "function" && e.name && keep.has(e.name));
  const found = new Set(out.map((e) => e.name));
  for (const n of names) if (!found.has(n)) throw new Error(`ABI ${artifact}: missing function ${n}`);
  return out;
}

const midnightAbi = loadAbi("Midnight.sol/Midnight.json", [
  "take",
  "supplyCollateral",
  "withdrawCollateral",
  "repay",
  "withdraw",
  "setIsAuthorized",
  "isAuthorized",
  "position",
  "marketState",
  "consumed",
  "credit",
  "debt",
  "collateral",
  "withdrawable",
  "isHealthy",
  "toMarket",
  "tickSpacing",
]);
const ratifierAbi = loadAbi("EcrecoverRatifier.sol/EcrecoverRatifier.json", [
  "isRatified",
  "cancelRoot",
  "isRootCanceled",
  "MIDNIGHT",
]);
const hashHelperAbi = loadAbi("HashHelper.sol/HashHelper.json", [
  "hashOffer",
  "digestSingle",
  "tickToPrice",
  "priceToTick",
]);
const erc20Abi = loadAbi("MockERC20.sol/MockERC20.json", [
  "mint",
  "approve",
  "allowance",
  "balanceOf",
  "decimals",
  "symbol",
]);
const oracleAbi = loadAbi("MockOracle.sol/MockOracle.json", ["price", "setPrice"]);

const zero = "0x0000000000000000000000000000000000000000";

const markets = deployments.markets.map((m: Record<string, unknown>) => ({
  id: m.id,
  loanSymbol: m.loanSymbol,
  loanDecimals: m.loanDecimals,
  collateralSymbol: m.collateralSymbol,
  collateralDecimals: m.collateralDecimals,
  oracle: m.oracle,
  market: {
    chainId: String(m.chainId),
    midnight: m.midnight,
    loanToken: m.loanToken,
    collateralParams: [
      {
        token: m.collateralToken,
        lltv: m.lltv,
        liquidationCursor: m.liquidationCursor,
        oracle: m.oracle,
      },
    ],
    maturity: m.maturity,
    rcfThreshold: m.rcfThreshold,
    enterGate: zero,
    liquidatorGate: zero,
  },
}));

const out = `// GENERATED by shared/gen.ts — do not edit. Re-run \`pnpm gen\` after deploying.
import type { MarketJSON } from "./types";

export const CHAIN_ID = ${deployments.chainId} as const;

export const ADDRESSES = {
  midnight: "${deployments.midnight}",
  ratifier: "${deployments.ratifier}",
  hashHelper: "${deployments.hashHelper}",
  tokens: ${JSON.stringify(deployments.tokens, null, 2)},
} as const;

export const DEPLOYED_AT = ${deployments.deployedAt};
export const MATURITY = "${deployments.maturity}";

export interface MarketInfo {
  id: string;
  loanSymbol: string;
  loanDecimals: number;
  collateralSymbol: string;
  collateralDecimals: number;
  oracle: string;
  market: MarketJSON;
}

export const MARKETS: MarketInfo[] = ${JSON.stringify(markets, null, 2)};

export const MIDNIGHT_ABI = ${JSON.stringify(midnightAbi)} as const;
export const RATIFIER_ABI = ${JSON.stringify(ratifierAbi)} as const;
export const HASH_HELPER_ABI = ${JSON.stringify(hashHelperAbi)} as const;
export const ERC20_ABI = ${JSON.stringify(erc20Abi)} as const;
export const ORACLE_ABI = ${JSON.stringify(oracleAbi)} as const;
`;

writeFileSync(join(here, "deployments.ts"), out);
console.log(`wrote shared/deployments.ts (${markets.length} markets, midnight=${deployments.midnight})`);
